---

zk-01:
  zookeeper_data_dir: /tmp/zookeeper
  zookeeper_port: 2181

zookeeper_download_dir: /home/juniour/Downloads/{{ kafka_version }}
zookeeper_deploy_dir: /opt
kafka_version: kafka_2.11-2.1.0
